# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            KPJ
tagline:          'Miscellanea'
description:      'Random pickings by <a href="https://twitter.com/the_pjonsson" target="_blank">@the_pjonsson</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Philip Jonsson'
  url:            https://twitter.com/the_pjonsson

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
  
  # Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider: google
  google: 
      tracking_id: 'UA-57835362-1'
  getclicky:
    site_id:
